# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ali stinkt

description: > # this means to ignore newlines until "baseurl:"
  Hey, das ist meine erste seite
baseurl: "" # the subpath of your site, e.g. /blog
url: "julisersteseite,de" # the base hostname & protocol for your site
twitter_username: Ful1
github_username: ItsFuli

# Build settings
markdown: kramdown
